name: Trade Station Build & Test

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Liberate disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Checkout Lean Same Branch
        id: lean-same-branch
        uses: actions/checkout@v2
        continue-on-error: true
        with:
          ref: ${{ github.ref }}
          repository: QuantConnect/Lean
          path: Lean

      - name: Checkout Lean Master
        if: steps.lean-same-branch.outcome != 'success'
        uses: actions/checkout@v2
        with:
          repository: QuantConnect/Lean
          path: Lean

      - name: Move Lean
        run: mv Lean ../Lean

      - uses: addnab/docker-run-action@v3
        with:
          image: quantconnect/lean:foundation
          options: --workdir /__w/Lean.Brokerages.TradeStation/Lean.Brokerages.TradeStation -v /home/runner/work:/__w -e QC_TRADE_STATION_CLIENT_ID=${{ env.QC_TRADE_STATION_CLIENT_ID }} -e QC_TRADE_STATION_CLIENT_SECRET=${{ env.QC_TRADE_STATION_CLIENT_SECRET }} -e QC_TRADE_STATION_ACCOUNT_TYPE=${{ env.QC_TRADE_STATION_ACCOUNT_TYPE }} -e QC_TRADE_STATION_REFRESH_TOKEN=${{ env.QC_TRADE_STATION_REFRESH_TOKEN }} -e QC_JOB_USER_ID=${{ env.QC_JOB_USER_ID }} -e QC_API_ACCESS_TOKEN=${{ env.QC_API_ACCESS_TOKEN }} -e QC_JOB_ORGANIZATION_ID=${{ env.QC_JOB_ORGANIZATION_ID }}
          shell: bash
          run: |
            # Build Trade Station Solution
            dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.TradeStationBrokerage.sln && \
            # Run Trade Station Tests
            dotnet test ./QuantConnect.TradeStationBrokerage.Tests/bin/Release/QuantConnect.Brokerages.TradeStation.Tests.dll
